
spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys?useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

shiro-redis:
  cluster:
    timeout: 10000
    host: localhost:6379
    name: user

